---
name: publish helm chart

on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
    inputs:
      tag:
        description: Release Tag
        required: true
        default: 0.0.0
        type: string
  release:
    types:
      - published

jobs:
  debug_actions:
    name: debug_actions
    runs-on: ubuntu-latest
    steps:
      - name: default token
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api rate_limit -q '.rate | (.reset |= todate)'
      - name: determined account token
        env:
          GH_TOKEN: ${{ secrets.DETERMINED_TOKEN }}
        run: |
          gh api rate_limit -q '.rate | (.reset |= todate)'
